package com.example.topmusic.model

sealed class Songs(val title: String, val artist: String)

class Rap(title: String, artist: String): Songs(title, artist)
class Pop(title: String, artist: String): Songs(title, artist)
class Rock(title: String, artist: String): Songs(title, artist)



object List{
    val popList = listOf(
        Pop("Truth Hurts", "Lizzo"),
        Pop("Senorita", "Shawn Mendes & Camila Cabello"),
        Pop("Someone You Loved", "Lewis Capaldi"),
        Pop("Goodbyes", "Post Malone Featuring Young Thug"),
        Pop("Only Human", "Jonas Brothers"),
        Pop("Circles", "Post Malone"),
        Pop("I Don't Care", "Ed Sheeran & Justin Bieber"),
        Pop("Beautiful People", "Ed Sheeran Featuring Khalid"),
        Pop("Trampoline", "SHAED"),
        Pop("Bad Guy", "Billie Eilish"),
        Pop("Talk", "Khalid"),
        Pop("How Do You Sleep?", "Sam Smith"),
        Pop("Sucker", "Jonas Brothers"),
        Pop("Time", "NF"),
        Pop("Good As Hell", "Lizzo"),
        Pop("Motivation", "Normani"),
        Pop("Graveyard", "Halsey"),
        Pop("Memories", "Maroon 5"),
        Pop("Liar", "Camila Cabello"),
        Pop("Panini", "Lil Nas X"),
        Pop("Lover", "Taylor Swift"),
        Pop("One Thing Right", "Marshmello & Kane Brown"),
        Pop("Boyfriend", "Ariana Grande & Social House"),
        Pop("Don't Call Me Angel (Charlie's Angels)", "Ariana Grande Miley Cyrus & Lana Del Rey"),
        Pop("No Guidance", "Chris Brown Featuring Drake"),
        Pop("Who Do U Love?", "MONSTA X & French Montana"),
        Pop("What Am I", "Why Don't We"),
        Pop("Ransom", "Lil Tecca"),
        Pop("10,000 Hours", "Dan + Shay & Justin Bieber"),
        Pop("Nice To Meet Ya", "Niall Horan"),
        Pop("Good Things Fall Apart", "Illenium & Jon Bellion"),
        Pop("Higher Love", "Kygo X Whitney Houston"),
        Pop("Shameless", "Camila Cabello"),
        Pop("Lonely", "Diplo Presents Thomas Wesley With Jonas Brothers"),
        Pop("My Type", "Saweetie"),
        Pop("Rooting For You", "Alessia Cara"),
        Pop("All The Good Girls Go To Hell", "Billie Eilish"),
        Pop("Hot Girl Summer", "Megan Thee Stallion, Nicki Minaj & Ty Dolla Sign"),
        Pop("Slow Dance", "AJ Mitchell & Ava Max"),
        Pop("Right Back","Khalid Featuring A Boogie Wit da Hoodie"))

    val rapList = listOf(
        Rap("HIGHEST IN THE ROOM"," Travis Scott"),
        Rap("Truth Hurts"," Lizzo"),
        Rap("Ransom"," Lil Tecca"),
        Rap("Panini"," Lil Nas X"),
        Rap("Bandit"," Juice WRLD & YoungBoy Never Broke Again"),
        Rap("Goodbyes"," Post Malone Featuring Young Thug"),
        Rap("Old Town Road"," Lil Nas X Featuring Billy Ray Cyrus"),
        Rap("Money In The Grave"," Drake Featuring Rick Ross"),
        Rap("On Chill"," Wale Featuring Jeremih"),
        Rap("Baby"," Lil Baby & DaBaby"),
        Rap("Ballin'", "Mustard Featuring Roddy Ricch"),
        Rap("Hot Girl Summer"," Megan Thee Stallion Nicki Minaj & Ty Dolla Sign"),
        Rap("INTRO"," DaBaby"),
        Rap("My Type"," Saweetie"),
        Rap("223's", "YNW Melly & 9lokknine"),
        Rap("Hot"," Young Thug Featuring Gunna"),
        Rap("Camelot"," NLE Choppa"),
        Rap("BOP"," DaBaby"),
        Rap("VIBEZ"," DaBaby"),
        Rap("Time"," NF"),
        Rap("Cash Shit"," Megan Thee Stallion Featuring DaBaby"),
        Rap("The London"," Young Thug, J. Cole & Travis Scott"),
        Rap("Enemies"," Post Malone Featuring DaBaby"),
        Rap("Hot Girl Bummer"," blackbear"),
        Rap("TOES"," DaBaby Featuring Lil Baby & Moneybagg Yo"))

    val rockList = listOf(
        Rock("High Hopes", "Panic! At The Disco"),
        Rock("Hey Look Ma, I Made It", "Panic! At The Disco"),
        Rock("The Hype", "twenty one pilots"),
        Rock("I Think I'm OKAY", "Machine Gun Kelly X YUNGBLUD X Travis Barker"),
        Rock("Here Comes The Sun", "The Beatles"),
        Rock("Father Of All...", "Green Day"),
        Rock("Social Cues", "Cage The Elephant"),
        Rock("Outnumbered", "Dermot Kennedy"),
        Rock("Come Together", "The Beatles"),
        Rock("Go", "The Black Keys"),
        Rock("16", "Highly Suspect"),
        Rock("Fear Inoculum", "Tool"),
        Rock("Under Your Scars", "Godsmack"),
        Rock("The End Of The Game", "Weezer"),
        Rock("White Room", "Cream"),
        Rock("Rock And Roll Part 2", "Gary Glitter"),
        Rock("we fell in love in october", "girl in red"),
        Rock("Dear Future Self (Hands Up)", "Fall Out Boy Featuring Wyclef Jean"),
        Rock("Unsainted", "Slipknot"),
        Rock("I Really Wish I Hated You", "Blink-182"),
        Rock("Something", "The Beatles"),
        Rock("10/10", "Rex Orange County"),
        Rock("Alligator", "Of Monsters And Men"),
        Rock("Sing Along", "Sturgill Simpson"),
        Rock("Running Up That Hill", "Meg Myers"),
        Rock("BLOW", "Ed Sheeran With Chris Stapleton & Bruno Mars"),
        Rock("Carry Me Away", "John Mayer"),
        Rock("Panic Attack", "The Glorious Sons"),
        Rock("Might Be Right", "White Reaper"),
        Rock("All My Friends", "Dermot Kennedy"),
        Rock("Die Happy", "DREAMERS"),
        Rock("Complainer", "Cold War Kids"),
        Rock("Legendary", "Skillet"),
        Rock("Last Day Under The Sun", "Volbeat"),
        Rock("When I'm Gone", "Dirty Honey"),
        Rock("When Am I Gonna Lose You", "Local Natives"),
        Rock("Pneuma", "Tool"),
        Rock("Life In The City", "The Lumineers"),
        Rock("High Steppin'", "The Avett Brothers"),
        Rock("Miracle Pill", "Goo Goo Dolls"),
        Rock("You'll Never Find Me", "Korn"),
        Rock("Prom Queen", "Beach Bunny"),
        Rock("Back Foot", "Dinosaur Pile-Up"),
        Rock("Miracle Man", "Oliver Tree"),
        Rock("Lost", "Dermot Kennedy"),
        Rock("Come Around", "Papa Roach"),
        Rock("Death Stranding", "CHVRCHES"),
        Rock("Don't Stop Me Now", "Queen"),
        Rock("Invincible", "Tool"),
        Rock("Birds", "Imagine Dragons Featuring Elisa"))
}